# Generated by Django 5.0 on 2024-11-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_polyencode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('local_lang_name',), 'verbose_name': 'Tokia', 'verbose_name_plural': 'Tokiak'},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Poligonoa', 'verbose_name_plural': 'Poligonoak'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='code',
            field=models.CharField(default='0', max_length=255, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Country language name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(default='s', max_length=255, verbose_name='Language Academy name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='local_lang_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Local language name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='official_name',
            field=models.CharField(default='a', max_length=255, verbose_name='Official name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Gehituta'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geotype',
            field=models.IntegerField(choices=[(0, 'Partzuergoa'), (1, 'Barrutia / Auzoa'), (2, 'Udalerria / Hiria'), (3, 'Bailara / Eskualdea'), (4, 'Probintzia'), (5, 'Estatua'), (6, 'Herrialdea')], db_index=True, default=0, verbose_name='Mota'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitudea'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitudea'),
        ),
        migrations.AlterField(
            model_name='place',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatuta'),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Oharrak'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_set', to='django_polyenco.Place', verbose_name='Gurasoa'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Gehituta'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_levels',
            field=models.TextField(blank=True, null=True, verbose_name='Kodetutako mailak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_numlevels',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodetzeko maila kopurua'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_points',
            field=models.TextField(blank=True, null=True, verbose_name='Kodetutako puntuak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_zoomfactor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodetzeko zoom faktorea'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_exterior',
            field=models.BooleanField(default=1, verbose_name='Kanpoaldekoa da'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_visible',
            field=models.BooleanField(default=1, verbose_name='Ikusgarria da'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='limits',
            field=models.TextField(blank=True, null=True, verbose_name='Mugak'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Editatuta'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_polyenco.Place', verbose_name='Tokia'),
        ),


        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('local_lang_name',), 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'verbose_name': 'Polygon', 'verbose_name_plural': 'Polygons'},
        ),
        migrations.AlterField(
            model_name='place',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country language name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geotype',
            field=models.IntegerField(choices=[(0, 'Consortium'), (1, 'District / Neighborhood'), (2, 'Town / City'), (3, 'Valley / Region'), (4, 'Province'), (5, 'State'), (6, 'Country')], db_index=True, default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language Academy name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='local_lang_name',
            field=models.CharField(max_length=255, verbose_name='Local language name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='place',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Official name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_set', to='django_polyencode.place', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_levels',
            field=models.TextField(blank=True, null=True, verbose_name='Encode levels'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_numlevels',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Encode number levels'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_points',
            field=models.TextField(blank=True, null=True, verbose_name='Encode points'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='encode_zoomfactor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Encode zoom factor'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_exterior',
            field=models.BooleanField(default=1, verbose_name='Is exterior'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='is_visible',
            field=models.BooleanField(default=1, verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='limits',
            field=models.TextField(blank=True, null=True, verbose_name='Limits'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_polyencode.place', verbose_name='Place'),
        ),
    ]
