# Generated by Django 5.0 on 2024-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_polyencode', '0005_auto_20230131_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country_lang_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country language name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lang_academ_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Language Academy name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='local_lang_name',
            field=models.CharField(max_length=255, verbose_name='Local language name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='place',
            name='official_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Official name'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Modified'),
        ),
    ]
